version: '2'
services:
  db:
    build: ./db
  search:
    image: elasticsearch
  logstash:
      image: logstash
  web:
    build: .
    command: npm start
    volumes:
      - .:/visfx
    ports:
      - "3000:3000"
    depends_on:
      - db
      - search
